implement multiply functionality
ecitizen-ke/naomi-calculator-flask pull request #3
Opened 2024-05-21 07:05 UTC by NaomiMunyiri

2024-05-21 21:10 UTC, MesfinGithinji approved these changes

2024-05-22 07:53 UTC, codetaskmaster commented on multiply_app/__init__.py
Add white space at the end of this file

2024-05-22 07:57 UTC, codetaskmaster requested changes

2024-05-22 07:57 UTC, maxwelbarno commented on multiply_app/routes.py
Add whitespace

2024-05-22 07:57 UTC, maxwelbarno commented on run.py
Add whitespace

2024-05-22 07:57 UTC, maxwelbarno commented on multiply_app/__pycache__/multiply.cpython-310.pyc
Ignore this file. Ensure it is deleted from your repository

2024-05-22 07:57 UTC, maxwelbarno commented on multiply_app/routes.py
> +    return jsonify({'result':result})
Add whitespace

2024-05-22 07:57 UTC, maxwelbarno commented on run.py
> +    app.run(debug=True)
Add whitespace

2024-05-22 07:59 UTC, codetaskmaster commented on run.py
> +    app.run(debug=True)
Hi @NaomiMunyiri, I have reviewed your code an left comments. Please work on them and let me know.
Happy Coding!

2024-05-22 08:33 UTC, NaomiMunyiri commented on run.py
> +    app.run(debug=True)
WIP

2024-05-22 08:50 UTC, codetaskmaster requested changes

2024-05-22 08:50 UTC, codetaskmaster commented on .gitignore
> +**/__pycache__/
Kindly add whitespace

2024-05-22 08:52 UTC, codetaskmaster approved these changes

2024-05-22 08:57 UTC, merged